user_timezone.settings:
  type: config_object
  label: 'User timezone settings'
  mapping:
    morning_start:
      type: integer
      label: 'Integer'
    morning_end:
      type: intteger
      label: 'Integer'
    afternoon_start:
      type: integer
      label: 'Integer'
    afternoon_end:
      type: integer
      label: 'Integer'
    evening_start:
      type: integer
      label: 'Integer'
    evening_end:
      type: integer
      label: 'Integer'
    night_start:
      type: integer
      label: 'Integer'
    night_end:
      type: integer
      label: 'Integer'
