<?php

/**
 * @file
 * This file adds/removes “Product uploader” role to the user upon registration...
 *
 * ...when the user’s email address contains/doesn't contain a “+productuploader”
 * fragment (e.g. johndoe+productuploaded@gmail.com).
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function product_uploader_user_presave(EntityInterface $entity): void {
  $fragment = '+productuploader';
  $email = $entity->getEmail();
  if (strpos($email, $fragment)) {
    $entity->addRole('product_uploader');
  }
  else {
    $entity->removeRole('product_uploader');
  }
}

/*https://red-route.org/articles/adding-roles-user-programmatically-drupal-8
 *https://drupal.stackexchange.com/questions/189210/how-do-i-assign-a-specific-role-to-each-newly-registered-user
 */
