<?php

/**
 * @file
 * This file adds/removes “Product uploader” role to the user upon registration.
 *
 * ...when the user’s email address contains/doesn't contain a “
 * +productuploader” fragment (e.g. johndoe+productuploaded@gmail.com).
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\product_uploader\ProductUploaderInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function product_uploader_user_presave(EntityInterface $entity): void {
  $email = $entity->getEmail();
  if (strpos($email, ProductUploaderInterface::PRODUCT_UPLOADER_FRAGMENT)) {
    $entity->addRole(ProductUploaderInterface::PRODUCT_UPLOADER_ROLE);
  }
  else {
    $entity->removeRole(ProductUploaderInterface::PRODUCT_UPLOADER_ROLE);
  }
}
