<?php

declare(strict_types = 1);

/**
 * @file
 * Contains hooks and callbacks for genre_validator.module.
 *
 * @param $fields
 * @param $entity_type
 * @param $bundle
 */
function genre_validator_entity_bundle_field_info_alter(
  /**
   * @param
   */
 array &$fields,
  /**
   * @param
   */
  $entity_type,
  /**
   * @param
   */
  $bundle) {

  if (
    $entity_type->id() === 'node') {
    if (
      $bundle === 'product') {
      if (isset($fields['field_genres'])) {
        $fields['field_genres']->addConstraint('genre_rules', []);
      }
    }
  }
}
