<?php

/**
 * @file
 * Creates taxonomy terms based on the Genres field's input.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\taxonomy\Entity\Term;

/**
 * Contains hooks and callbacks for genres_to_terms.module.
 */
function genres_to_terms_entity_presave(EntityInterface $entity): void {
  if ($entity instanceof NodeInterface && $entity->bundle() === 'product') {
    unset($entity->field_genre_tags);
    $vid = 'genres';
    $terms = Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vid);
    $inputs = explode(PHP_EOL, $entity->get('field_genres')->value);
    $termnames = [];
    foreach ($terms as $term) {
      $termnames[$term->name] = $term;
    }
    $term_ids = [];
    foreach ($inputs as $input) {
      if (empty($termnames[$input])) {
        $term = Term::create([
          'name' => $input,
          'vid' => 'genres',
        ]);
        $term->save();
      }
      $assign = Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties(['name' => $input, 'vid' => 'genres']);
      $assign = reset($assign);
      $assign_id = $assign->id();
      $term_ids[] = ['target_id' => $assign_id];
    }
    $entity->set('field_genre_tags', $term_ids);
  }
}
